from datetime import datetime, timezone
from app import db


class LaptopRequest(db.Model):
    __tablename__ = "laptop_requests"

    id = db.Column(db.Integer, primary_key=True)

    # Requester
    requester_name = db.Column(db.String(120), nullable=False)
    requester_email = db.Column(db.String(200), nullable=False)

    # Employee being provisioned for (may differ from requester)
    employee_name = db.Column(db.String(120), nullable=False)
    employee_email = db.Column(db.String(200), nullable=False)
    department = db.Column(db.String(120), nullable=False)

    # Manager
    manager_name = db.Column(db.String(120), nullable=False)
    manager_email = db.Column(db.String(200), nullable=False)

    # Laptop details
    laptop_model = db.Column(db.String(120), nullable=True)
    asset_tag = db.Column(db.String(60), nullable=True)
    priority = db.Column(db.String(20), nullable=False, default="normal")  # low/normal/high/urgent
    notes = db.Column(db.Text, nullable=True)

    # Oracle reference (optional – links back to existing Oracle ticket)
    oracle_ref = db.Column(db.String(80), nullable=True)

    # Workflow status
    STATUS_PENDING = "pending"
    STATUS_APPROVED = "approved"
    STATUS_REJECTED = "rejected"
    STATUS_IN_PROGRESS = "in_progress"
    STATUS_DISPATCHED = "dispatched"
    STATUS_DELIVERED = "delivered"
    STATUS_CANCELLED = "cancelled"

    status = db.Column(db.String(30), nullable=False, default="pending")

    # Timestamps
    created_at = db.Column(db.DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    approved_at = db.Column(db.DateTime(timezone=True), nullable=True)
    dispatched_at = db.Column(db.DateTime(timezone=True), nullable=True)
    delivered_at = db.Column(db.DateTime(timezone=True), nullable=True)

    # Relationships
    audit_logs = db.relationship("AuditLog", back_populates="request", lazy="dynamic",
                                 cascade="all, delete-orphan")
    approval_tokens = db.relationship("ApprovalToken", back_populates="request", lazy="dynamic",
                                      cascade="all, delete-orphan")

    def status_label(self) -> str:
        return self.status.replace("_", " ").title()

    def __repr__(self) -> str:
        return f"<LaptopRequest #{self.id} {self.employee_name} [{self.status}]>"


class ApprovalToken(db.Model):
    """
    Short-lived signed token embedded in approval/rejection email links.
    The token is a URL-safe string generated by itsdangerous; this model
    records that a token was issued (for audit purposes) and whether it
    has been consumed.
    """
    __tablename__ = "approval_tokens"

    id = db.Column(db.Integer, primary_key=True)
    request_id = db.Column(db.Integer, db.ForeignKey("laptop_requests.id"), nullable=False)
    token = db.Column(db.String(512), unique=True, nullable=False)
    action = db.Column(db.String(10), nullable=False)  # "approve" or "reject"
    created_at = db.Column(db.DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    used_at = db.Column(db.DateTime(timezone=True), nullable=True)
    used_by_ip = db.Column(db.String(50), nullable=True)

    request = db.relationship("LaptopRequest", back_populates="approval_tokens")

    def __repr__(self) -> str:
        return f"<ApprovalToken request={self.request_id} action={self.action}>"


class AuditLog(db.Model):
    """Immutable audit trail – one row per status change or manual action."""
    __tablename__ = "audit_logs"

    id = db.Column(db.Integer, primary_key=True)
    request_id = db.Column(db.Integer, db.ForeignKey("laptop_requests.id"), nullable=False)
    actor = db.Column(db.String(200), nullable=False)   # email or "system"
    action = db.Column(db.String(80), nullable=False)   # e.g. "status_changed_to_approved"
    detail = db.Column(db.Text, nullable=True)
    timestamp = db.Column(db.DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

    request = db.relationship("LaptopRequest", back_populates="audit_logs")

    def __repr__(self) -> str:
        return f"<AuditLog request={self.request_id} {self.action}>"
